# Generated by Django 3.0.6 on 2020-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Super Admin'), (2, 'Vendor')], default=1),
        ),
    ]
